import Route from '@ember/routing/route';

export default Route.extend({

  model(params) {
    const people = [{
      "id": 1,
      "first_name": "Saundra",
      "last_name": "Manuaud",
      "email": "smanuaud0@twitpic.com",
      "gender": "Female",
      "ip_address": "227.104.109.77"
    }, {
      "id": 2,
      "first_name": "Wilbur",
      "last_name": "Heinish",
      "email": "wheinish1@virginia.edu",
      "gender": "Male",
      "ip_address": "217.72.63.196"
    }, {
      "id": 3,
      "first_name": "Lalo",
      "last_name": "Bengall",
      "email": "lbengall2@google.com.au",
      "gender": "Male",
      "ip_address": "143.175.71.172"
    }, {
      "id": 4,
      "first_name": "Leoline",
      "last_name": "Loos",
      "email": "lloos3@artisteer.com",
      "gender": "Female",
      "ip_address": "48.190.241.91"
    }, {
      "id": 5,
      "first_name": "Sharl",
      "last_name": "Schruyer",
      "email": "sschruyer4@blogs.com",
      "gender": "Female",
      "ip_address": "37.85.128.30"
    }, {
      "id": 6,
      "first_name": "Deborah",
      "last_name": "Cardenoso",
      "email": "dcardenoso5@ifeng.com",
      "gender": "Female",
      "ip_address": "7.121.73.127"
    }, {
      "id": 7,
      "first_name": "Garrard",
      "last_name": "Youthead",
      "email": "gyouthead6@digg.com",
      "gender": "Male",
      "ip_address": "86.129.14.236"
    }, {
      "id": 8,
      "first_name": "Kaleb",
      "last_name": "Melluish",
      "email": "kmelluish7@live.com",
      "gender": "Male",
      "ip_address": "132.215.6.192"
    }, {
      "id": 9,
      "first_name": "Lyndsey",
      "last_name": "Haggerstone",
      "email": "lhaggerstone8@hc360.com",
      "gender": "Female",
      "ip_address": "161.233.134.208"
    }, {
      "id": 10,
      "first_name": "Mathilda",
      "last_name": "Abreheart",
      "email": "mabreheart9@cbsnews.com",
      "gender": "Female",
      "ip_address": "57.171.248.87"
    }, {
      "id": 11,
      "first_name": "Coreen",
      "last_name": "Summerly",
      "email": "csummerlya@bloglovin.com",
      "gender": "Female",
      "ip_address": "113.158.192.167"
    }, {
      "id": 12,
      "first_name": "Pietrek",
      "last_name": "Royston",
      "email": "proystonb@upenn.edu",
      "gender": "Male",
      "ip_address": "223.153.89.184"
    }, {
      "id": 13,
      "first_name": "Marlee",
      "last_name": "Duquesnay",
      "email": "mduquesnayc@squarespace.com",
      "gender": "Female",
      "ip_address": "48.172.27.118"
    }, {
      "id": 14,
      "first_name": "Katerina",
      "last_name": "Fluger",
      "email": "kflugerd@nature.com",
      "gender": "Female",
      "ip_address": "160.172.144.115"
    }, {
      "id": 15,
      "first_name": "Saba",
      "last_name": "Attrey",
      "email": "sattreye@shutterfly.com",
      "gender": "Female",
      "ip_address": "15.210.25.49"
    }, {
      "id": 16,
      "first_name": "Alfie",
      "last_name": "Burbridge",
      "email": "aburbridgef@prlog.org",
      "gender": "Female",
      "ip_address": "133.58.220.206"
    }, {
      "id": 17,
      "first_name": "Federico",
      "last_name": "Staries",
      "email": "fstariesg@vkontakte.ru",
      "gender": "Male",
      "ip_address": "166.106.149.51"
    }, {
      "id": 18,
      "first_name": "Dotti",
      "last_name": "Deners",
      "email": "ddenersh@quantcast.com",
      "gender": "Female",
      "ip_address": "19.182.159.110"
    }, {
      "id": 19,
      "first_name": "Belita",
      "last_name": "Jaggar",
      "email": "bjaggari@japanpost.jp",
      "gender": "Female",
      "ip_address": "148.108.164.227"
    }, {
      "id": 20,
      "first_name": "Umberto",
      "last_name": "Bramble",
      "email": "ubramblej@independent.co.uk",
      "gender": "Male",
      "ip_address": "45.124.39.153"
    }, {
      "id": 21,
      "first_name": "Onida",
      "last_name": "Hebson",
      "email": "ohebsonk@shareasale.com",
      "gender": "Female",
      "ip_address": "95.117.233.199"
    }, {
      "id": 22,
      "first_name": "Obediah",
      "last_name": "Delagua",
      "email": "odelagual@washington.edu",
      "gender": "Male",
      "ip_address": "0.126.211.46"
    }, {
      "id": 23,
      "first_name": "Milly",
      "last_name": "Kiellor",
      "email": "mkiellorm@1688.com",
      "gender": "Female",
      "ip_address": "68.198.4.57"
    }, {
      "id": 24,
      "first_name": "Ilene",
      "last_name": "Aldwich",
      "email": "ialdwichn@multiply.com",
      "gender": "Female",
      "ip_address": "204.23.203.0"
    }, {
      "id": 25,
      "first_name": "Bondie",
      "last_name": "Dockray",
      "email": "bdockrayo@ucoz.com",
      "gender": "Male",
      "ip_address": "61.60.44.86"
    }];
    return people[params.id];
  }

});